-- Create user feedback table following database_standard.md
CREATE TABLE IF NOT EXISTS `t_user_feedback` (
    `id` BIGINT NOT NULL COMMENT '主键，雪花ID',
    `user_id` BIGINT NOT NULL COMMENT '提交用户ID',
    `feedback_type` VARCHAR(20) DEFAULT NULL COMMENT '反馈类型：BUG_ISSUE-问题/BUG，FEATURE_REQUEST-功能建议，CONTENT-内容质量问题，ACCOUNT-账号问题，OTHER-其他',
    `feedback_source` VARCHAR(20) NOT NULL DEFAULT 'MINI_PROGRAM' COMMENT '反馈来源：APP-APP内，MINI_PROGRAM-小程序，WEB-网页，H5-移动H5，OFFLINE-线下',
    `title` VARCHAR(100) DEFAULT NULL COMMENT '反馈标题',
    `content` TEXT NOT NULL COMMENT '反馈内容',
    `contact` VARCHAR(100) DEFAULT NULL COMMENT '联系方式（手机号/邮箱/微信号等）',
    `is_contactable` TINYINT DEFAULT NULL DEFAULT 1 COMMENT '是否允许联系：0-否 1-是',
    `status` VARCHAR(20) DEFAULT NULL DEFAULT 'PENDING' COMMENT '处理状态：PENDING-待处理，IN_PROGRESS-处理中，RESOLVED-已解决，REJECTED-已驳回',
    `priority` VARCHAR(10) DEFAULT NULL DEFAULT 'MEDIUM' COMMENT '优先级：LOW-低，MEDIUM-中，HIGH-高',
    `app_version` VARCHAR(50) NULL COMMENT '客户端版本号',
    `device_model` VARCHAR(100) NULL COMMENT '设备型号',
    `os_type` VARCHAR(20) NULL COMMENT '操作系统：ANDROID/IOS/WEB/OTHER',
    `os_version` VARCHAR(50) NULL COMMENT '操作系统版本',
    `attach_urls` TEXT NULL COMMENT '附件地址（JSON数组字符串，包含截图/录屏等）',
    `processed_by` BIGINT NULL COMMENT '处理人ID（运营/客服）',
    `processed_time` DATETIME NULL COMMENT '处理时间',
    `remark` VARCHAR(500) NULL COMMENT '处理备注',
    `create_by` VARCHAR(50) NOT NULL DEFAULT 'system',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_by` VARCHAR(50) NOT NULL DEFAULT 'system',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除：0-否 1-是',
    PRIMARY KEY (`id`),
    KEY `idx_user_feedback_user` (`user_id`),
    KEY `idx_user_feedback_status` (`status`),
    KEY `idx_user_feedback_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户反馈表';
